second release to production
savaukr/resume pull request #4
Opened 2021-01-09 15:51 UTC by savaukr

2021-01-09 15:52 UTC, savaukr reviewed
ok

2021-01-09 15:53 UTC, savaukr reviewed
ok

2021-01-09 16:16 UTC, savabinary commented
я не знаю як пslndthlbnb

2021-01-09 16:31 UTC, savabinary reviewed
the end

2021-01-09 16:31 UTC, savabinary commented on README.md
> +# Resume (edited)
ok

2021-01-09 16:31 UTC, savabinary commented on index.html
> +<!DOCTYPE html>
ok

2021-01-09 16:34 UTC, savaukr commented
ok

2021-01-10 15:09 UTC, savabinary reviewed
I am reviewed

2021-01-10 15:10 UTC, savabinary reviewed
I am reviewed

2021-01-10 15:16 UTC, savabinary requested changes
Finally, i understanded, how it works

2021-01-10 15:17 UTC, savabinary requested changes
All right

2021-01-10 15:17 UTC, savabinary approved these changes

2021-01-10 15:18 UTC, merged